import './sass/main.scss';
import './js/example-api';
import './js/load-popular-main';
import './js/pagination';
import './js/modal';
import './js/load-films-by-query';
import './js/theme';
import './js/team';
import './js/components/spinner';
